export const popularShows = {
  page: 1,
  results: [
    {
      adult: false,
      backdrop_path: "/N1hWzVPpZ8lIQvQskgdQogxdsc.jpg",
      id: 84958,
      name: "Loki",
      original_language: "en",
      original_name: "Loki",
      overview:
        "After stealing the Tesseract during the events of “Avengers: Endgame,” an alternate version of Loki is brought to the mysterious Time Variance Authority, a bureaucratic organization that exists outside of time and space and monitors the timeline. They give Loki a choice: face being erased from existence due to being a “time variant” or help fix the timeline and stop a greater threat.",
      poster_path: "/voHUmluYmKyleFkTu3lOXQG702u.jpg",
      media_type: "tv",
      genre_ids: [18, 10765],
      popularity: 2729.472,
      first_air_date: "2021-06-09",
      vote_average: 8.176,
      vote_count: 10645,
      origin_country: ["US"],
    },
    {
      adult: false,
      backdrop_path: "/rqbCbjB19amtOtFQbb3K2lgm2zv.jpg",
      id: 1429,
      name: "Attack on Titan",
      original_language: "ja",
      original_name: "進撃の巨人",
      overview:
        "Several hundred years ago, humans were nearly exterminated by Titans. Titans are typically several stories tall, seem to have no intelligence, devour human beings and, worst of all, seem to do it for the pleasure rather than as a food source. A small percentage of humanity survived by walling themselves in a city protected by extremely high walls, even taller than the biggest Titans. Flash forward to the present and the city has not seen a Titan in over 100 years. Teenage boy Eren and his foster sister Mikasa witness something horrific as the city walls are destroyed by a Colossal Titan that appears out of thin air. As the smaller Titans flood the city, the two kids watch in horror as their mother is eaten alive. Eren vows that he will murder every single Titan and take revenge for all of mankind.",
      poster_path: "/hTP1DtLGFamjfu8WqjnuQdP1n4i.jpg",
      media_type: "tv",
      genre_ids: [16, 10765, 10759],
      popularity: 230.992,
      first_air_date: "2013-04-07",
      vote_average: 8.664,
      vote_count: 5654,
      origin_country: ["JP"],
    },
    {
      adult: false,
      backdrop_path: "/5caSC8v35IwURAByAh7WmXXEDSF.jpg",
      id: 134095,
      name: "A Murder at the End of the World",
      original_language: "en",
      original_name: "A Murder at the End of the World",
      overview:
        "Gen Z amateur sleuth and tech-savvy hacker Darby Hart and eight other guests are invited by a reclusive billionaire to participate in a retreat at a remote location. When one of the other guests is found dead, Darby must use her skills to prove it was murder before the killer takes another life.",
      poster_path: "/1mWCXJefbNU1E2XPJVM2vejMSZO.jpg",
      media_type: "tv",
      genre_ids: [9648, 18],
      popularity: 68.893,
      first_air_date: "2023-11-14",
      vote_average: 10.0,
      vote_count: 1,
      origin_country: ["US"],
    },
    {
      adult: false,
      backdrop_path: "/x9Pg2mugTXYynx6rYCJRWTWVCwG.jpg",
      id: 112388,
      name: "Beacon 23",
      original_language: "en",
      original_name: "Beacon 23",
      overview:
        "Aster Calyx and Halan Kai Nelson are inextricably drawn to Beacon 23. Navigating one threat after another, they unravel the beacon’s mysteries, just in time to face their most powerful enemy.",
      poster_path: "/iflPBIRvxeyXw1RlTqmI7yGtbP5.jpg",
      media_type: "tv",
      genre_ids: [10765, 18],
      popularity: 101.646,
      first_air_date: "2023-11-12",
      vote_average: 9.6,
      vote_count: 5,
      origin_country: ["US"],
    },
    {
      adult: false,
      backdrop_path: "/a6ptrTUH1c5OdWanjyYtAkOuYD0.jpg",
      id: 37854,
      name: "One Piece",
      original_language: "ja",
      original_name: "ワンピース",
      overview:
        'Years ago, the fearsome Pirate King, Gol D. Roger was executed leaving a huge pile of treasure and the famous "One Piece" behind. Whoever claims the "One Piece" will be named the new King of the Pirates.\n\nMonkey D. Luffy, a boy who consumed a "Devil Fruit," decides to follow in the footsteps of his idol, the pirate Shanks, and find the One Piece. It helps, of course, that his body has the properties of rubber and that he\'s surrounded by a bevy of skilled fighters and thieves to help him along the way.\n\nLuffy will do anything to get the One Piece and become King of the Pirates!',
      poster_path: "/fcXdJlbSdUEeMSJFsXKsznGwwok.jpg",
      media_type: "tv",
      genre_ids: [10759, 35, 16],
      popularity: 122.384,
      first_air_date: "1999-10-20",
      vote_average: 8.724,
      vote_count: 4156,
      origin_country: ["JP"],
    },
    {
      adult: false,
      backdrop_path: "/vi0TpQbbZ8FWTRBmawbvegMRbtc.jpg",
      id: 87917,
      name: "For All Mankind",
      original_language: "en",
      original_name: "For All Mankind",
      overview:
        "Explore an aspirational world where NASA and the space program remained a priority and a focal point of our hopes and dreams as told through the lives of NASA astronauts, engineers, and their families.",
      poster_path: "/mNXT1QjRCEasXGH3rHCTQm0A0Su.jpg",
      media_type: "tv",
      genre_ids: [18, 10765, 10768],
      popularity: 284.486,
      first_air_date: "2019-11-01",
      vote_average: 7.726,
      vote_count: 529,
      origin_country: ["US"],
    },
    {
      adult: false,
      backdrop_path: "/rBF8wVQN8hTWHspVZBlI3h7HZJ.jpg",
      id: 60625,
      name: "Rick and Morty",
      original_language: "en",
      original_name: "Rick and Morty",
      overview:
        "Rick is a mentally-unbalanced but scientifically gifted old man who has recently reconnected with his family. He spends most of his time involving his young grandson Morty in dangerous, outlandish adventures throughout space and alternate universes. Compounded with Morty's already unstable family life, these events cause Morty much distress at home and school.",
      poster_path: "/gdIrmf2DdY5mgN6ycVP0XlzKzbE.jpg",
      media_type: "tv",
      genre_ids: [16, 35, 10765, 10759],
      popularity: 1136.444,
      first_air_date: "2013-12-02",
      vote_average: 8.701,
      vote_count: 8756,
      origin_country: ["US"],
    },
    {
      adult: false,
      backdrop_path: "/d783DAdVCRy5O5nsSDJ5MMFLi28.jpg",
      id: 114655,
      name: "The Curse",
      original_language: "en",
      original_name: "The Curse",
      overview:
        "An alleged curse disturbs the relationship of a newly married couple as they try to conceive a child while co-starring on their problematic new HGTV show.",
      poster_path: "/k2qJPaGFdyFXEEJpwG5HrmeNpjv.jpg",
      media_type: "tv",
      genre_ids: [35],
      popularity: 180.032,
      first_air_date: "2023-11-12",
      vote_average: 10.0,
      vote_count: 5,
      origin_country: ["US"],
    },
    {
      adult: false,
      backdrop_path: "/hU0w2cSvSYoTYHpm3MacasT6cxa.jpg",
      id: 235350,
      name: "Suburræterna",
      original_language: "it",
      original_name: "Suburræterna",
      overview:
        'While chaos rules over Rome, established alliances are at risk as tensions rise with emerging criminal clans. The world of "Suburra" takes a new turn.',
      poster_path: "/uAHqkArr7HAxGoHKJnsg92DKqhj.jpg",
      media_type: "tv",
      genre_ids: [80, 18],
      popularity: 38.529,
      first_air_date: "2023-11-14",
      vote_average: 7.0,
      vote_count: 1,
      origin_country: ["IT"],
    },
    {
      adult: false,
      backdrop_path: "/xzuUDxZqT2Y1faH0XHXjTzplAMR.jpg",
      id: 235924,
      name: "Criminal Code",
      original_language: "pt",
      original_name: "DNA do Crime",
      overview:
        "To crack the code of an investigation into a larger-than-life robbery, federal agents need to get creative.",
      poster_path: "/fDu0T5WE0QAoX2yAqZ1RtlWBn6I.jpg",
      media_type: "tv",
      genre_ids: [18, 80, 10759],
      popularity: 43.38,
      first_air_date: "2023-11-14",
      vote_average: 0.0,
      vote_count: 0,
      origin_country: ["BR"],
    },
    {
      adult: false,
      backdrop_path: "/gmECX1DvFgdUPjtio2zaL8BPYPu.jpg",
      id: 95479,
      name: "Jujutsu Kaisen",
      original_language: "ja",
      original_name: "呪術廻戦",
      overview:
        "Yuji Itadori is a boy with tremendous physical strength, though he lives a completely ordinary high school life. One day, to save a classmate who has been attacked by curses, he eats the finger of Ryomen Sukuna, taking the curse into his own soul. From then on, he shares one body with Ryomen Sukuna. Guided by the most powerful of sorcerers, Satoru Gojo, Itadori is admitted to Tokyo Jujutsu High School, an organization that fights the curses... and thus begins the heroic tale of a boy who became a curse to exorcise a curse, a life from which he could never turn back.",
      poster_path: "/hFWP5HkbVEe40hrXgtCeQxoccHE.jpg",
      media_type: "tv",
      genre_ids: [16, 10759, 10765],
      popularity: 727.031,
      first_air_date: "2020-10-03",
      vote_average: 8.564,
      vote_count: 2897,
      origin_country: ["JP"],
    },
    {
      adult: false,
      backdrop_path: "/6UH52Fmau8RPsMAbQbjwN3wJSCj.jpg",
      id: 95557,
      name: "Invincible",
      original_language: "en",
      original_name: "Invincible",
      overview:
        "Mark Grayson is a normal teenager except for the fact that his father is the most powerful superhero on the planet. Shortly after his seventeenth birthday, Mark begins to develop powers of his own and enters into his father’s tutelage.",
      poster_path: "/dMOpdkrDC5dQxqNydgKxXjBKyAc.jpg",
      media_type: "tv",
      genre_ids: [16, 10765, 10759, 18],
      popularity: 678.109,
      first_air_date: "2021-03-25",
      vote_average: 8.668,
      vote_count: 3840,
      origin_country: ["US"],
    },
    {
      adult: false,
      backdrop_path: "/xmQMrlYc3IlzpDMPKtfl9sVf7mw.jpg",
      id: 157732,
      name: "Lawmen: Bass Reeves",
      original_language: "en",
      original_name: "Lawmen: Bass Reeves",
      overview:
        "The story of Bass Reeves, the legendary lawman of the wild West, is brought to life. Reeves worked in the post-Reconstruction era as a federal peace officer in the Indian Territory, capturing over 3,000 of the most dangerous criminals without ever being wounded—and is believed to be the inspiration for The Lone Ranger.",
      poster_path: "/g5YvjqykQe2ZZK1C6qBXrM9EG1i.jpg",
      media_type: "tv",
      genre_ids: [18],
      popularity: 246.915,
      first_air_date: "2023-11-05",
      vote_average: 8.1,
      vote_count: 8,
      origin_country: ["US"],
    },
    {
      adult: false,
      backdrop_path: "/aCROH2L1yTeRe3im0XOYiUbI2YJ.jpg",
      id: 205715,
      name: "Gen V",
      original_language: "en",
      original_name: "Gen V",
      overview:
        "At America's only college for superheroes, gifted students put their moral boundaries to the test, competing for the university's top ranking, and a chance to join The Seven, Vought International's elite superhero team. When the school's dark secrets come to light, they must decide what kind of heroes they want to become.",
      poster_path: "/uuot1N5AgZ7xRCKgm4ZCwOhgIJu.jpg",
      media_type: "tv",
      genre_ids: [10765, 10759, 18],
      popularity: 702.421,
      first_air_date: "2023-09-28",
      vote_average: 8.002,
      vote_count: 419,
      origin_country: ["US"],
    },
    {
      adult: false,
      backdrop_path: "/2OMB0ynKlyIenMJWI2Dy9IWT4c.jpg",
      id: 1399,
      name: "Game of Thrones",
      original_language: "en",
      original_name: "Game of Thrones",
      overview:
        "Seven noble families fight for control of the mythical land of Westeros. Friction between the houses leads to full-scale war. All while a very ancient evil awakens in the farthest north. Amidst the war, a neglected military order of misfits, the Night's Watch, is all that stands between the realms of men and icy horrors beyond.",
      poster_path: "/1XS1oqL89opfnbLl8WnZY1O1uJx.jpg",
      media_type: "tv",
      genre_ids: [10765, 18, 10759],
      popularity: 662.154,
      first_air_date: "2011-04-17",
      vote_average: 8.4,
      vote_count: 22093,
      origin_country: ["US"],
    },
    {
      adult: false,
      backdrop_path: "/5OQEDTtB32RAjzyT1Q28TdPUtyM.jpg",
      id: 155421,
      name: "All the Light We Cannot See",
      original_language: "en",
      original_name: "All the Light We Cannot See",
      overview:
        "The story of Marie-Laure, a blind teenager, and Werner, a German soldier, whose paths collide in occupied France as both try to survive the devastation of World War II.",
      poster_path: "/5vctOvdEXakZWTJrP8bgPEoCbqS.jpg",
      media_type: "tv",
      genre_ids: [18],
      popularity: 168.06,
      first_air_date: "2023-11-02",
      vote_average: 7.592,
      vote_count: 76,
      origin_country: ["US"],
    },
    {
      adult: false,
      backdrop_path: "/5r0jTtBYNYlwhO5vhP3ekrS8SBc.jpg",
      id: 157950,
      name: "NCIS: Sydney",
      original_language: "en",
      original_name: "NCIS: Sydney",
      overview:
        "The brilliant and eclectic team of U.S. NCIS Agents and the Australian Federal Police (AFP) are grafted into a multi-national taskforce to keep naval crimes in check in the most contested patch of ocean on the planet.",
      poster_path: "/rUND1AfEcUIkoxnS3fmIpMChpiu.jpg",
      media_type: "tv",
      genre_ids: [80, 18, 10759],
      popularity: 51.185,
      first_air_date: "2023-11-10",
      vote_average: 10.0,
      vote_count: 6,
      origin_country: ["AU"],
    },
    {
      adult: false,
      backdrop_path: "/zNugnnR5KEmq9EzLcl0Me1UmHYk.jpg",
      id: 120089,
      name: "SPY x FAMILY",
      original_language: "ja",
      original_name: "SPY×FAMILY",
      overview:
        "World peace is at stake and secret agent Twilight must undergo his most difficult mission yet—pretend to be a family man. Posing as a loving husband and father, he’ll infiltrate an elite school to get close to a high-profile politician. He has the perfect cover, except his wife’s a deadly assassin and neither knows each other’s identity. But someone does, his adopted daughter who’s a telepath!",
      poster_path: "/7NAvPYPAu7MeHwP8E9sn81PqsRh.jpg",
      media_type: "tv",
      genre_ids: [16, 35, 10759],
      popularity: 338.816,
      first_air_date: "2022-04-09",
      vote_average: 8.6,
      vote_count: 1519,
      origin_country: ["JP"],
    },
    {
      adult: false,
      backdrop_path: "/2fhnFgwbpqzhNsx5m9x7JEUQ2qv.jpg",
      id: 86248,
      name: "Upload",
      original_language: "en",
      original_name: "Upload",
      overview:
        "In 2033, people who are near death can be “uploaded” into virtual reality hotels run by 6 tech firms. Cash-strapped Nora lives in Brooklyn and works customer service for the luxurious “Lakeview” digital afterlife. When L.A. party-boy/coder Nathan’s self-driving car crashes, his high-maintenance girlfriend uploads him permanently into Nora’s VR world.",
      poster_path: "/6TPGDrU9MyWbn2TpggJphVAVXiq.jpg",
      media_type: "tv",
      genre_ids: [35, 10765],
      popularity: 224.5,
      first_air_date: "2020-04-30",
      vote_average: 8.0,
      vote_count: 1030,
      origin_country: ["US"],
    },
    {
      adult: false,
      backdrop_path: "/oGkh6ByqaSKXlW6SkIOBXJWvLan.jpg",
      id: 225180,
      name: "BLUE EYE SAMURAI",
      original_language: "en",
      original_name: "BLUE EYE SAMURAI",
      overview:
        "Driven by a dream of revenge against those who made her an outcast in Edo-period Japan, a young warrior cuts a bloody path toward her destiny.",
      poster_path: "/fXm3JT4WLQVnwukdvghtAblc1wc.jpg",
      media_type: "tv",
      genre_ids: [10759, 16, 18],
      popularity: 178.995,
      first_air_date: "2023-11-03",
      vote_average: 8.424,
      vote_count: 46,
      origin_country: ["US"],
    },
  ],
  total_pages: 1000,
  total_results: 20000,
};
